package com.example.JournalApplication.scheduler;

import com.example.JournalApplication.cache.AppCache;
import com.example.JournalApplication.entity.JournalEntry;
import com.example.JournalApplication.entity.UserEntity;
import com.example.JournalApplication.repository.UserRepositoryImpl;
import com.example.JournalApplication.service.EmailService;
import com.example.JournalApplication.service.SentimentAnalysisService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class UserScheduler {
    @Autowired
    private EmailService emailService;

    @Autowired
    private UserRepositoryImpl userRepository;

    @Autowired
    private SentimentAnalysisService sentimentAnalysisService;

    @Autowired
    private AppCache appCache;

    /* Cron Expression is every week Tuesday 12 : 26 p.m. run this. Such Cron Expression
    can be generated by http://www.cronmaker.com/;jsessionid=node0zj0jo5sjikjjoy5zgll2z1sm355850.node0?0

    Also please @EnableScheduling in JournalApplication.java to note that below function is a scheduler
     */
    @Scheduled(cron = "0 26 12 ? * TUE")
    public void fetUsersAndSendSaMail(){
        List<UserEntity> usersForSA = userRepository.getUsersForSA();

        for (UserEntity user : usersForSA){
            List<JournalEntry> journalEntries = user.getJournalEntries();
            List<String> filteredList = journalEntries.stream().filter(x->x.getDate().isAfter(LocalDateTime.now().minus(7, ChronoUnit.DAYS))).map(x->x.getContent()).collect(Collectors.toList());
            String entry = String.join(" ",filteredList);
            String sentiment = sentimentAnalysisService.getSentiment(entry);
            emailService.sendEmail(user.getEmail(),"Sentiment for Last 7 days ", sentiment);
        }
    }

    /* Cron Expression is every 5 minutes run this. Such Cron Expression
    can be generated by http://www.cronmaker.com/;jsessionid=node0zj0jo5sjikjjoy5zgll2z1sm355850.node0?0

    Also please @EnableScheduling in JournalApplication.java to note that below function is a scheduler
     */
    @Scheduled(cron = "0 0/5 * 1/1 * ?")
    public void clearAppCahe(){
        appCache.init();
    }
}
